### PR TITLE
fixing bug

### PR DESCRIPTION
**Pull request by fssalmaie**
i hide user field if instructor want to register

### CODE REVIEW

**Comment by almarzouq** [comment]
When u hide any field that is a foreign key, you must set its value using initial, or set it when u save the form

**Comment by almarzouq** [comment]
Test this and make sure it works, I suspect it will not work correctly

**Comment by fssalmaie** [comment]
before i pushed the work 
first i added user field in forms as "forms.HiddenInput" but when i tested it did not work 
so i removed it and fixing it through view function "fields" required i did not put it as a required
when i test this one it's worked

**Comment by almarzouq** [comment]
when u add it as hidden, you have to the set the user value

all u have to do is set it when create the empty form like this:

```
form = InstructorForm(initial={'user':request.user})
```

**Pull request merged**
